"""empty message

Revision ID: b596d5e761b0
Revises: 211257f3d159
Create Date: 2024-02-21 14:10:02.682238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b596d5e761b0'
down_revision = '211257f3d159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trashcan_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trashcan_table')
    # ### end Alembic commands ###
